openapi: 3.0.1
info:
  title: The Open Food Network
  description: Before testing, log into staging.katuma.org with the email 
    spree@example.com and password spree123.
    https://github.com/openfoodfoundation/openfoodnetwork
  version: '0.1'
servers:
  - url: 'http://staging.katuma.org'
paths:
  /api/products:
    get:
      description: Get all products <3
      responses:
        '200':
          description: successful operation
      
  /api/products/{product_id}:
    get:
      summary: Get a product by ID
      parameters:
        - in: path
          name: product_id
          schema:
            type: integer
          required: true
          description: Numeric ID of the product
      description: Gets all products
      responses:
        '200':
          description: successful operation