openapi: 3.0.1
info:
  title: The Open Food Network
  description: Before testing, log into staging.katuma.org with the email 
    spree@example.com and password spree123.
    https://github.com/openfoodfoundation/openfoodnetwork
  version: '0.1'
servers:
  - url: 'http://staging.katuma.org'
  - url: 'https://staging.katuma.org/api/'
paths:
  /api/products:
    get:
      description: Get all products <3
      responses:
        '200':
          description: successful operation
      
  /api/products/{product_id}:
    get:
      summary: Get a product by ID
      parameters:
        - in: path
          name: product_id
          schema:
            type: integer
          required: true
          description: Numeric ID of the product
      description: Gets all products
      responses:
        '200':
          description: successful operation
          
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        presentation:
          type: string
        option_type_name:
          type: string
        option_type_id:
          type: integer
          format: int64