openapi: 3.0.1
info:
  title: The Open Food Network
  description: Before testing, log into staging.katuma.org with the email 
    spree@example.com and password spree123.
    https://github.com/openfoodfoundation/openfoodnetwork
  version: '0.1'
servers:
  - url: 'https://staging.katuma.org/api/'
  - url: 'https://staging.katuma.org/api/'
paths:
  /products:
    get:
      description: Get all products
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      description: Posts a new product
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
      
  /products/{product_id}:
    get:
      description: Get a product by ID
      parameters:
        - in: path
          name: product_id
          schema:
            type: integer
          required: true
          description: Numeric ID of the product
      responses:
        '200':
          description: successful operation
    put:
      description: Replaces the product at the given ID
      parameters:
          - in: path
            name: product_id
            schema:
              type: integer
            required: true
            description: Numeric ID of the product
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    delete:
      description: Deletes the product at the given ID
      parameters:
          - in: path
            name: product_id
            schema:
              type: integer
            required: true
            description: Numeric ID of the product
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'     
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
  schemas:
    Product:
      type: object
      properties:
        id: 
          type: integer
        name: 
          type: string
        description: 
          type: string
        price: 
          type: string
        available_on: 
          type: string
        permalink: 
          type: string
        count_on_hand: 
          type: integer
        meta_description: 
          type: string
        meta_keywords: 
          type: string
        taxon_ids: 
          type: object
        variants: 
          type: object
        option_types: 
          type: object
        product_properties: 
          type: object
    Variant:
      type: object
      properties:
        id: 
          type: integer
        name: 
          type: string
        count_on_hand: 
          type: integer
        sku: 
          type: string
        price: 
          type: string
        weight: 
          type: string
        height: 
          type: string
        width: 
          type: string
        depth: 
          type: string
        is_master: 
          type: string
        cost_price: 
          type: string
        permalink: 
          type: string
        option_values: 
          type: object
        images: 
          type: object
    Zone:
      type: object
      properties:
        id: 
          type: integer
        description: 
          type: string
        zone_members: 
          type: object
        name: 
          type: string
    Taxonomy:
      type: object
      properties:
        root: 
          type: object
        id: 
          type: integer
        name: 
          type: string